#!/bin/sh

# do nothing if there are changes to commit
if [ -z "$(git status --porcelain)" ]; then
  exit 0
fi

black dags/

sqlfluff fix \
  --dialect redshift \
  --ignore parsing,templating dags/sql_redshift/